name: price_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  another_stepper: ^1.2.2
  staggered_grid_view_flutter: ^0.0.4
  flutter_svg_provider: ^1.0.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoLight.ttf
          weight: 300
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayLight.ttf
          weight: 300
