import 'bloc/intro_one_one_bloc.dart';import 'models/intro_one_one_model.dart';import 'package:flutter/material.dart';import 'package:price_s_application2/core/app_export.dart';import 'package:price_s_application2/widgets/custom_outlined_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class IntroOneOneScreen extends StatelessWidget {const IntroOneOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<IntroOneOneBloc>(create: (context) => IntroOneOneBloc(IntroOneOneState(introOneOneModelObj: IntroOneOneModel()))..add(IntroOneOneInitialEvent()), child: IntroOneOneScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<IntroOneOneBloc, IntroOneOneState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 60.v), Text("msg_discover_something".tr, style: CustomTextStyles.titleLargeProductSansBlack900Bold), SizedBox(height: 22.v), Text("msg_special_new_arrivals".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 31.v), SizedBox(height: 621.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [_buildShoppingNowSection(context), _buildFrameSection(context)]))]))));}); } 
/// Section Widget
Widget _buildShoppingNowSection(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 65.h, vertical: 73.v), decoration: AppDecoration.fillGray, child: Column(mainAxisSize: MainAxisSize.min, children: [Opacity(opacity: 0.40167412, child: Container(height: 25.v, width: 237.h, decoration: BoxDecoration(color: appTheme.gray9007e, borderRadius: BorderRadius.circular(12.h)))), SizedBox(height: 57.v), SizedBox(height: 6.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: appTheme.whiteA700, dotHeight: 6.v, dotWidth: 6.h))), SizedBox(height: 27.v), CustomOutlinedButton(text: "lbl_shopping_now".tr, margin: EdgeInsets.only(left: 21.h, right: 14.h), buttonStyle: CustomButtonStyles.outlineWhiteA), SizedBox(height: 37.v)]))); } 
/// Section Widget
Widget _buildFrameSection(BuildContext context) { return Align(alignment: Alignment.topRight, child: GestureDetector(onTap: () {onTapFrameSection(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [Container(height: 368.v, width: 261.h, padding: EdgeInsets.symmetric(horizontal: 21.h), decoration: AppDecoration.fillGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomImageView(imagePath: ImageConstant.imgKisspngModelF, height: 349.v, width: 217.h, alignment: Alignment.bottomCenter)), CustomImageView(imagePath: ImageConstant.imgRectangle2675264x25, height: 264.v, width: 25.h, margin: EdgeInsets.only(left: 32.h, top: 61.v, bottom: 43.v))]))); } 
/// Navigates to the introTwoOneScreen when the action is triggered.
onTapFrameSection(BuildContext context) { NavigatorService.pushNamed(AppRoutes.introTwoOneScreen, ); } 
 }
