import '../intro_two_one_screen/widgets/shoppingnowframe_item_widget.dart';import 'bloc/intro_two_one_bloc.dart';import 'models/intro_two_one_model.dart';import 'models/shoppingnowframe_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:price_s_application2/core/app_export.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class IntroTwoOneScreen extends StatelessWidget {const IntroTwoOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<IntroTwoOneBloc>(create: (context) => IntroTwoOneBloc(IntroTwoOneState(introTwoOneModelObj: IntroTwoOneModel()))..add(IntroTwoOneInitialEvent()), child: IntroTwoOneScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 60.v), Text("msg_update_trendy_outfit".tr, style: CustomTextStyles.titleLargeProductSansBlack900Bold), SizedBox(height: 22.v), Text("msg_favorite_brands".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 32.v), Align(alignment: Alignment.centerLeft, child: SizedBox(height: 621.v, width: 536.h, child: Stack(alignment: Alignment.bottomRight, children: [_buildShoppingNowFrame(context), Align(alignment: Alignment.bottomRight, child: BlocBuilder<IntroTwoOneBloc, IntroTwoOneState>(builder: (context, state) {return Container(height: 6.v, margin: EdgeInsets.only(right: 170.h, bottom: 190.v), child: AnimatedSmoothIndicator(activeIndex: state.sliderIndex, count: state.introTwoOneModelObj?.shoppingnowframeItemList.length ?? 0, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 8, dotColor: appTheme.whiteA700, dotHeight: 6.v, dotWidth: 6.h)));}))])))])))); } 
/// Section Widget
Widget _buildShoppingNowFrame(BuildContext context) { return BlocBuilder<IntroTwoOneBloc, IntroTwoOneState>(builder: (context, state) {return CarouselSlider.builder(options: CarouselOptions(height: 621.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {state.sliderIndex = index;}), itemCount: state.introTwoOneModelObj?.shoppingnowframeItemList.length ?? 0, itemBuilder: (context, index, realIndex) {ShoppingnowframeItemModel model = state.introTwoOneModelObj?.shoppingnowframeItemList[index] ?? ShoppingnowframeItemModel(); return ShoppingnowframeItemWidget(model, onTapFashionPng: () {onTapFashionPng(context);});});}); } 
/// Navigates to the introThreeOneScreen when the action is triggered.
onTapFashionPng(BuildContext context) { NavigatorService.pushNamed(AppRoutes.introThreeOneScreen, ); } 
 }
